version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - 3000:3000

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 5173:5173