import { CosmonautType } from "~~/model/ cosmonaut";

export const cosmonaut: CosmonautType[] = [
  {
    id: 1,
    firstname: "Sergey",
    lastname: "Prokopyev",
    namespace: "sergeyprokopyev",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 2,
    firstname: "Dmitry",
    lastname: "Petelin",
    namespace: "dmitrypetelin",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 3,
    firstname: "Frank",
    lastname: "Rubio",
    namespace: "frankrubio",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 4,
    firstname: "Nicole",
    lastname: "Mann",
    namespace: "nicolemann",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 5,
    firstname: "Josh",
    lastname: "Cassada",
    namespace: "joshcassada",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 6,
    firstname: "Koichi",
    lastname: "Wakata",
    namespace: "koichiwakata",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 7,
    firstname: "Anna",
    lastname: "Kikina",
    namespace: "annakikina",
    inSpace: true,
    craft: "ISS",
  },
  {
    id: 8,
    firstname: "Fei",
    lastname: "Junlong",
    namespace: "feijunlong",
    inSpace: true,
    craft: "Shenzhou 15",
  },
  {
    id: 9,
    firstname: "Deng",
    lastname: "Qingming",
    namespace: "dengqingming",
    inSpace: true,
    craft: "Shenzhou 15",
  },
  {
    id: 10,
    firstname: "Zhang",
    lastname: "Lu",
    namespace: "zhanglu",
    inSpace: true,
    craft: "Shenzhou 15",
  },
];
